import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { 
  Package, CheckCircle2, TrendingUp, ArrowRight, UploadCloud, 
  FileSpreadsheet, AlertTriangle, Eraser, Play, Loader2, Check, ArrowLeft, Sparkles, Trophy,
  BarChart3, PieChart, Activity, X, FileText, Cpu, Layers
} from 'lucide-react';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, 
  ComposedChart, Line, Legend, Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis 
} from 'recharts';

// --- Types & Constants ---
type WorkflowStage = 'UPLOAD' | 'CLEANING' | 'SELECTION' | 'TRAINING' | 'RESULT';

const AVAILABLE_MODELS = [
  { id: 'xgboost', name: 'XGBoost', type: 'Ensemble', recommended: true },
  { id: 'lightgbm', name: 'LightGBM', type: 'Ensemble', recommended: true },
  { id: 'rf', name: 'Random Forest', type: 'Bagging', recommended: false },
  { id: 'linear', name: 'Linear Regression', type: 'Linear', recommended: false },
  { id: 'mlp', name: 'MLP Neural Net', type: 'Deep Learning', recommended: false },
];

interface ModelResult {
    id: string;
    name: string;
    type: string;
    accuracy: number;
    r2: number;
    status: string;
    rmse: number;
    mae: number;
}

// --- Mock Data ---

const PREDICTION_DATA = [
    { month: '1月', actual: 4000, predicted: 4100, residual: 100 },
    { month: '2月', actual: 3000, predicted: 2950, residual: -50 },
    { month: '3月', actual: 2000, predicted: 2100, residual: 100 },
    { month: '4月', actual: 2780, predicted: 2908, residual: 128 },
    { month: '5月', actual: 1890, predicted: 1800, residual: -90 },
    { month: '6月', actual: 2390, predicted: 2450, residual: 60 },
    { month: '7月', actual: 3490, predicted: 3400, residual: -90 },
    { month: '8月', actual: 4200, predicted: 4350, residual: 150 },
];

const FEATURE_IMPORTANCE_DATA = [
  { name: '历史销量_Lag1', importance: 85 },
  { name: '促销力度', importance: 65 },
  { name: '节假日因子', importance: 45 },
  { name: '竞品价格', importance: 30 },
  { name: '平均气温', importance: 25 },
  { name: '库存周转', importance: 15 },
];

const RADAR_DATA = [
  { subject: '准确性', A: 92, B: 70, fullMark: 100 },
  { subject: '训练速度', A: 75, B: 90, fullMark: 100 },
  { subject: '推理解释性', A: 60, B: 85, fullMark: 100 },
  { subject: '抗噪能力', A: 85, B: 60, fullMark: 100 },
  { subject: '部署轻量度', A: 80, B: 95, fullMark: 100 },
];

const HYPERPARAMETERS = [
    { param: 'n_estimators', value: '1000' },
    { param: 'learning_rate', value: '0.05' },
    { param: 'max_depth', value: '6' },
    { param: 'subsample', value: '0.8' },
    { param: 'colsample_bytree', value: '0.8' },
    { param: 'gamma', value: '0.1' }
];

// --- Components ---

const DetailedReportModal: React.FC<{ 
    isOpen: boolean; 
    onClose: () => void; 
    modelName: string;
    isUnfit: boolean;
}> = ({ isOpen, onClose, modelName, isUnfit }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 backdrop-blur-sm">
            <div className="bg-white w-full max-w-4xl h-[85vh] flex flex-col border-2 border-black shadow-[12px_12px_0px_0px_rgba(0,0,0,1)]">
                {/* Header */}
                <div className="flex justify-between items-center p-6 border-b-2 border-black bg-gray-50">
                    <div className="flex items-center gap-3">
                        <div className="bg-black text-white p-2">
                            <FileText className="w-6 h-6" />
                        </div>
                        <div>
                            <h2 className="text-2xl font-black uppercase">详细评估报告</h2>
                            <p className="text-xs font-mono text-gray-600">Generated by AiLM AutoML Engine • {new Date().toLocaleDateString()}</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-gray-200 border-2 border-transparent hover:border-black transition-all">
                        <X className="w-6 h-6" />
                    </button>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-auto p-8 bg-white">
                    {/* Executive Summary */}
                    <div className="mb-8">
                        <h3 className="text-lg font-bold border-l-4 border-black pl-3 mb-4 uppercase">1. 执行摘要</h3>
                        <p className="font-mono text-sm leading-relaxed text-gray-700">
                            本次训练共评估了 5 个候选模型。最终 <span className="font-bold text-black">{modelName}</span> 在验证集上表现最佳。
                            {isUnfit 
                                ? " ⚠️ 警告：模型各项指标均未达到预设的生产部署阈值，建议重新审查数据质量或增加特征维度。" 
                                : " 模型各项指标稳健，未发现明显的过拟合现象，建议进行部署。"}
                        </p>
                    </div>

                    {/* Metrics Grid */}
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                        {[
                            { label: 'MSE (均方误差)', value: '1240.5' },
                            { label: 'RMSE (均方根误差)', value: '35.2' },
                            { label: 'MAE (平均绝对误差)', value: '28.4' },
                            { label: 'MAPE (平均百分比误差)', value: '4.2%' },
                        ].map((m, i) => (
                            <div key={i} className="border-2 border-black p-4 bg-gray-50">
                                <p className="text-xs font-bold text-gray-500 uppercase mb-1">{m.label}</p>
                                <p className="text-xl font-black font-mono">{m.value}</p>
                            </div>
                        ))}
                    </div>

                    {/* Residual Analysis */}
                    <div className="mb-8">
                        <h3 className="text-lg font-bold border-l-4 border-black pl-3 mb-4 uppercase">2. 残差分布分析</h3>
                        <div className="h-64 border border-black p-4">
                             <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={PREDICTION_DATA}>
                                    <CartesianGrid strokeDasharray="3 3" vertical={false} />
                                    <XAxis dataKey="month" tick={{fontSize: 10}} />
                                    <YAxis />
                                    <Tooltip contentStyle={{ border: '2px solid black' }} />
                                    <Legend />
                                    <Bar dataKey="residual" name="残差 (预测偏差)" fill="#000000" />
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                        <p className="text-xs text-gray-500 mt-2 font-mono">
                            * 残差应呈现以0为中心的随机正态分布。如果呈现特定趋势，说明模型遗漏了某些规律。
                        </p>
                    </div>

                    {/* Hyperparameters */}
                    <div>
                        <h3 className="text-lg font-bold border-l-4 border-black pl-3 mb-4 uppercase">3. 最佳超参数配置</h3>
                        <div className="grid grid-cols-2 gap-x-8 gap-y-2 font-mono text-sm border-2 border-black p-6 bg-gray-50">
                            {HYPERPARAMETERS.map((h, i) => (
                                <div key={i} className="flex justify-between border-b border-gray-300 pb-1">
                                    <span className="text-gray-600">{h.param}</span>
                                    <span className="font-bold">{h.value}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                {/* Footer */}
                <div className="p-6 border-t-2 border-black bg-gray-50 flex justify-end gap-4">
                    <button onClick={onClose} className="px-6 py-3 font-bold uppercase hover:underline">关闭</button>
                    <button className="bg-black text-white px-6 py-3 border-2 border-black font-bold uppercase hover:bg-white hover:text-black transition-colors">
                        导出 PDF
                    </button>
                </div>
            </div>
        </div>
    );
};

export const AutoML: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  
  // Project Info
  const projectName = location.state?.projectName || '未命名 AutoML 项目';
  const isUnfitProject = projectName.includes('未拟合');

  // Initial state based on navigation (default to UPLOAD for new projects)
  const [stage, setStage] = useState<WorkflowStage>(location.state?.stage || 'UPLOAD');
  
  // Workflow State
  const [file, setFile] = useState<File | null>(null);
  const [error, setError] = useState('');
  const [isCleaning, setIsCleaning] = useState(false);
  const [dataCleaned, setDataCleaned] = useState(false);
  const [selectedModels, setSelectedModels] = useState<string[]>(['xgboost', 'lightgbm']);
  const [trainingProgress, setTrainingProgress] = useState(0);
  
  // Result View State
  const [results, setResults] = useState<ModelResult[]>([]);
  const [selectedResultModel, setSelectedResultModel] = useState<string>('');
  const [isPackaged, setIsPackaged] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<string>('');
  
  // Visualization Tabs
  const [activeVizTab, setActiveVizTab] = useState<'fit' | 'feature' | 'radar'>('fit');
  const [reportOpen, setReportOpen] = useState(false);

  // --- Handlers ---

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const uploadedFile = e.target.files?.[0];
    setError('');
    if (!uploadedFile) return;
    if (uploadedFile.size === 0) {
        setError('文件内容为空，请上传有效数据。');
        return;
    }
    const ext = uploadedFile.name.split('.').pop()?.toLowerCase();
    if (!['csv', 'xlsx', 'xls'].includes(ext || '')) {
        setError('仅支持 CSV 或 Excel 格式。');
        return;
    }
    setFile(uploadedFile);
  };

  const startCleaning = () => {
      setIsCleaning(true);
      setTimeout(() => {
          setIsCleaning(false);
          setDataCleaned(true);
      }, 1500);
  };

  const toggleModel = (id: string) => {
      setSelectedModels(prev => 
        prev.includes(id) ? prev.filter(m => m !== id) : [...prev, id]
      );
  };

  const startTraining = () => {
      setStage('TRAINING');
      setTrainingProgress(0);
  };

  // Simulate Training Progress
  useEffect(() => {
      if (stage === 'TRAINING') {
          const interval = setInterval(() => {
              setTrainingProgress(prev => {
                  if (prev >= 100) {
                      clearInterval(interval);
                      setTimeout(() => setStage('RESULT'), 500);
                      return 100;
                  }
                  return prev + 5; // increment
              });
          }, 200);
          return () => clearInterval(interval);
      }
  }, [stage]);

  // Generate Results and Analysis when entering RESULT stage
  useEffect(() => {
      if (stage === 'RESULT' && results.length === 0) {
          generateResults();
      }
  }, [stage]);

  const generateResults = () => {
      let modelsToRun = selectedModels;
      if (modelsToRun.length === 0) {
          modelsToRun = ['xgboost', 'lightgbm', 'rf']; 
      }
      
      const generatedResults: ModelResult[] = modelsToRun.map(id => {
          const template = AVAILABLE_MODELS.find(m => m.id === id)!;
          let baseAcc, baseR2;
          if (isUnfitProject) {
              baseAcc = 40 + Math.random() * 20; 
              baseR2 = 0.2 + Math.random() * 0.3;
          } else {
              baseAcc = 85 + Math.random() * 10;
              baseR2 = 0.8 + Math.random() * 0.15;
          }

          return {
              id: id,
              name: template.name,
              type: template.type,
              accuracy: parseFloat(baseAcc.toFixed(1)),
              r2: parseFloat(baseR2.toFixed(2)),
              status: isUnfitProject ? '收敛(效果差)' : '已收敛',
              rmse: 35.2 + Math.random() * 10,
              mae: 28.4 + Math.random() * 5
          };
      });

      generatedResults.sort((a, b) => b.accuracy - a.accuracy);
      setResults(generatedResults);
      if (generatedResults.length > 0) {
          setSelectedResultModel(generatedResults[0].id);
      }

      if (isUnfitProject) {
          setAiAnalysis(`
**警报：模型拟合效果不佳**

根据评估结果，所有选中模型的准确率均低于 **60%**。

**问题诊断：**
1. **数据相关性低**：特征与目标变量之间缺乏强相关性。
2. **特征缺失**：可能缺少关键的业务特征。
          `);
      } else {
          const winner = generatedResults[0];
          setAiAnalysis(`
**模型表现优秀**

经过 AutoML 引擎评估，**${winner.name}** 模型表现最佳，测试集准确率达到 **${winner.accuracy}%**。

**分析摘要：**
- **${winner.name}** 在当前结构化数据集上表现出了极强的泛化能力。
- R2 Score 为 ${winner.r2}，表明模型解释了绝大部分的数据变异。
          `);
      }
  };


  // --- Render Helpers ---

  const renderStepper = () => {
      const steps: {id: WorkflowStage, label: string}[] = [
          { id: 'UPLOAD', label: '上传数据' },
          { id: 'CLEANING', label: '数据清洗' },
          { id: 'SELECTION', label: '选择模型' },
          { id: 'TRAINING', label: '建模中' },
          { id: 'RESULT', label: '模型结果' }
      ];

      return (
          <div className="flex justify-between items-center mb-8 border-b-2 border-black pb-6 px-4">
              {steps.map((s, idx) => {
                  const isCurrent = s.id === stage;
                  const isPast = steps.findIndex(step => step.id === stage) > idx;
                  
                  return (
                      <div key={s.id} className="flex flex-col items-center relative z-10 w-24">
                          <div className={`w-8 h-8 rounded-full border-2 flex items-center justify-center mb-2 font-bold text-xs transition-colors
                              ${isCurrent ? 'bg-black text-white border-black' : ''}
                              ${isPast ? 'bg-gray-200 border-black text-black' : ''}
                              ${!isCurrent && !isPast ? 'bg-white border-gray-300 text-gray-300' : ''}
                          `}>
                              {isPast ? <Check className="w-4 h-4" /> : idx + 1}
                          </div>
                          <span className={`text-xs font-bold uppercase ${isCurrent || isPast ? 'text-black' : 'text-gray-300'}`}>{s.label}</span>
                      </div>
                  )
              })}
          </div>
      );
  };

  const renderBackButton = () => (
      <button 
        onClick={() => navigate('/dashboard')}
        className="flex items-center gap-2 text-black font-bold mb-6 hover:underline text-sm w-fit"
      >
        <ArrowLeft className="w-4 h-4" />
        返回仪表盘
      </button>
  );

  // --- VIEW: UPLOAD ---
  if (stage === 'UPLOAD') {
      return (
          <div className="p-8 max-w-4xl mx-auto">
              {renderBackButton()}
              {renderStepper()}
              <div className="bg-white border-2 border-black p-8 text-center min-h-[400px] flex flex-col items-center justify-center">
                  <h2 className="text-2xl font-black uppercase mb-2">步骤 1: 上传训练数据</h2>
                  <p className="text-gray-600 font-mono text-sm mb-8">支持 CSV, Excel (.xlsx) 格式。请确保包含表头。</p>
                  
                  <label className="cursor-pointer group">
                      <input type="file" className="hidden" accept=".csv,.xlsx,.xls" onChange={handleFileUpload} />
                      <div className="w-64 h-48 border-2 border-black border-dashed flex flex-col items-center justify-center bg-gray-50 group-hover:bg-gray-100 transition-colors">
                          <UploadCloud className="w-12 h-12 mb-4 text-black" />
                          <span className="font-bold uppercase text-sm">点击选择文件</span>
                      </div>
                  </label>

                  {error && (
                      <div className="mt-6 flex items-center gap-2 text-red-600 border border-red-500 bg-red-50 px-4 py-2">
                          <AlertTriangle className="w-4 h-4" />
                          <span className="text-sm font-bold">{error}</span>
                      </div>
                  )}

                  {file && !error && (
                      <div className="mt-6 w-full max-w-md">
                          <div className="flex items-center gap-3 border-2 border-black p-3 bg-white">
                              <FileSpreadsheet className="w-6 h-6" />
                              <div className="flex-1 text-left">
                                  <p className="font-bold text-sm truncate">{file.name}</p>
                                  <p className="text-xs text-gray-500 font-mono">{(file.size / 1024).toFixed(2)} KB</p>
                              </div>
                              <CheckCircle2 className="w-5 h-5 text-green-600" />
                          </div>
                          <button 
                            onClick={() => setStage('CLEANING')}
                            className="w-full mt-4 bg-black text-white border-2 border-black py-3 font-bold uppercase hover:bg-white hover:text-black transition-colors"
                          >
                              解析并下一步
                          </button>
                      </div>
                  )}
              </div>
          </div>
      );
  }

  // --- VIEW: CLEANING ---
  if (stage === 'CLEANING') {
      return (
          <div className="p-8 max-w-4xl mx-auto">
              {renderBackButton()}
              {renderStepper()}
              <div className="bg-white border-2 border-black p-8">
                  <h2 className="text-2xl font-black uppercase mb-6">步骤 2: 数据质量检查</h2>
                  <div className="grid grid-cols-2 gap-6 mb-8">
                      <div className="p-4 bg-gray-50 border border-black">
                          <p className="text-xs font-bold uppercase text-gray-500 mb-1">行数 (Rows)</p>
                          <p className="text-2xl font-mono font-bold">12,450</p>
                      </div>
                      <div className="p-4 bg-gray-50 border border-black">
                          <p className="text-xs font-bold uppercase text-gray-500 mb-1">特征数 (Features)</p>
                          <p className="text-2xl font-mono font-bold">18</p>
                      </div>
                  </div>
                  {!dataCleaned ? (
                      <div className="border border-red-200 bg-red-50 p-6 mb-8">
                          <div className="flex items-start gap-3">
                              <AlertTriangle className="w-6 h-6 text-red-600 shrink-0" />
                              <div>
                                  <h3 className="font-bold text-red-800 mb-2">发现数据问题</h3>
                                  <ul className="list-disc list-inside text-sm text-red-700 font-mono space-y-1">
                                      <li>3 列存在缺失值 (Total: 450)</li>
                                      <li>发现 2 个重复 ID</li>
                                      <li>"Date" 列格式不统一</li>
                                  </ul>
                              </div>
                          </div>
                      </div>
                  ) : (
                      <div className="border border-green-200 bg-green-50 p-6 mb-8">
                           <div className="flex items-start gap-3">
                              <CheckCircle2 className="w-6 h-6 text-green-600 shrink-0" />
                              <div>
                                  <h3 className="font-bold text-green-800 mb-2">数据清洗完成</h3>
                                  <p className="text-sm text-green-700 font-mono">
                                      已自动填充缺失值 (Mean)，删除重复项，并标准化日期格式。数据现已准备就绪。
                                  </p>
                              </div>
                          </div>
                      </div>
                  )}
                  <div className="flex justify-end gap-4">
                      {!dataCleaned ? (
                          <button 
                            onClick={startCleaning}
                            disabled={isCleaning}
                            className="flex items-center gap-2 bg-white text-black border-2 border-black px-6 py-3 font-bold uppercase hover:bg-gray-100"
                          >
                              {isCleaning ? <Loader2 className="w-4 h-4 animate-spin" /> : <Eraser className="w-4 h-4" />}
                              {isCleaning ? '正在清洗...' : '自动清洗数据'}
                          </button>
                      ) : (
                          <button 
                             onClick={() => setStage('SELECTION')}
                             className="flex items-center gap-2 bg-black text-white border-2 border-black px-8 py-3 font-bold uppercase hover:bg-white hover:text-black transition-colors"
                          >
                              下一步: 模型选择
                              <ArrowRight className="w-4 h-4" />
                          </button>
                      )}
                  </div>
              </div>
          </div>
      );
  }

  // --- VIEW: SELECTION ---
  if (stage === 'SELECTION') {
      return (
          <div className="p-8 max-w-4xl mx-auto">
              {renderBackButton()}
              {renderStepper()}
              <div className="bg-white border-2 border-black p-8">
                  <h2 className="text-2xl font-black uppercase mb-2">步骤 3: 选择算法</h2>
                  <p className="text-gray-600 font-mono text-sm mb-6">AutoML 将并行训练选中的模型并进行超参数调优。</p>
                  <div className="space-y-3 mb-8">
                      {AVAILABLE_MODELS.map(model => (
                          <div 
                            key={model.id}
                            onClick={() => toggleModel(model.id)}
                            className={`flex items-center justify-between p-4 border-2 cursor-pointer transition-all ${
                                selectedModels.includes(model.id) ? 'border-black bg-gray-50' : 'border-transparent hover:bg-gray-50 border-gray-100'
                            }`}
                          >
                              <div className="flex items-center gap-4">
                                  <div className={`w-5 h-5 border-2 border-black flex items-center justify-center ${selectedModels.includes(model.id) ? 'bg-black' : 'bg-white'}`}>
                                      {selectedModels.includes(model.id) && <Check className="w-3 h-3 text-white" />}
                                  </div>
                                  <div>
                                      <p className="font-bold text-sm">{model.name}</p>
                                      <p className="text-xs text-gray-500 font-mono">{model.type}</p>
                                  </div>
                              </div>
                              {model.recommended && (
                                  <span className="text-[10px] font-bold uppercase bg-black text-white px-2 py-1">推荐</span>
                              )}
                          </div>
                      ))}
                  </div>
                  <div className="flex justify-end">
                      <button 
                        onClick={startTraining}
                        disabled={selectedModels.length === 0}
                        className="flex items-center gap-2 bg-black text-white border-2 border-black px-8 py-3 font-bold uppercase hover:bg-white hover:text-black transition-colors disabled:opacity-50"
                      >
                          <Play className="w-4 h-4" />
                          开始建模
                      </button>
                  </div>
              </div>
          </div>
      );
  }

  // --- VIEW: TRAINING ---
  if (stage === 'TRAINING') {
      return (
          <div className="p-8 max-w-4xl mx-auto">
               {renderBackButton()}
               {renderStepper()}
               <div className="bg-white border-2 border-black p-12 text-center">
                   <h2 className="text-2xl font-black uppercase mb-8">正在训练模型...</h2>
                   <div className="w-full h-8 border-2 border-black p-1 mb-4">
                       <div 
                         className="h-full bg-black transition-all duration-200" 
                         style={{ width: `${trainingProgress}%` }}
                       ></div>
                   </div>
                   <p className="font-mono text-right font-bold text-lg mb-8">{trainingProgress}%</p>
                   <div className="bg-gray-50 border border-black p-4 font-mono text-xs text-left h-48 overflow-y-auto space-y-2">
                       <p>&gt; Initializing AutoML engine...</p>
                       <p>&gt; Loading dataset (12,450 rows)...</p>
                       {trainingProgress > 10 && <p>&gt; [System] Starting parallel training on selected models...</p>}
                       {trainingProgress > 30 && <p>&gt; [Training] Cross-validation fold 2/5 complete...</p>}
                       {trainingProgress > 50 && <p>&gt; [Tuning] Hyperparameter optimization in progress...</p>}
                       {trainingProgress > 90 && <p>&gt; Finalizing model ensemble...</p>}
                   </div>
               </div>
          </div>
      );
  }

  // --- VIEW: RESULT ---
  const handlePackage = () => setIsPackaged(true);
  const topModelId = results.length > 0 ? results[0].id : '';
  const currentModelName = results.find(m => m.id === selectedResultModel)?.name || 'Unknown';

  return (
    <div className="p-8 max-w-7xl mx-auto h-full flex flex-col relative">
      <DetailedReportModal 
        isOpen={reportOpen} 
        onClose={() => setReportOpen(false)} 
        modelName={currentModelName}
        isUnfit={isUnfitProject}
      />

      {renderBackButton()}

      {/* Header */}
      <div className="flex justify-between items-center mb-8 border-b-2 border-black pb-6">
        <div>
           <div className="flex items-center gap-2 mb-1">
             <span className="px-2 py-0.5 border border-black text-[10px] font-bold uppercase bg-gray-100">AutoML 回归任务</span>
             {isUnfitProject && <span className="px-2 py-0.5 border border-red-600 text-red-600 text-[10px] font-bold uppercase bg-red-50">数据质量警告</span>}
           </div>
           <h1 className="text-2xl font-black text-black">{projectName}</h1>
           <p className="text-gray-600 font-mono text-sm mt-1">&gt; 状态: 训练完成 ({results.length}个模型)</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
         {/* Left: Visualization & Charts */}
         <div className="lg:col-span-2 space-y-8">
            
            {/* AI Analysis Card */}
            <div className={`border-2 border-black p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] ${isUnfitProject ? 'bg-red-50' : 'bg-yellow-50'}`}>
                <div className="flex items-center gap-2 mb-4 border-b-2 border-black border-dashed pb-2">
                    <Sparkles className="w-5 h-5 text-black" />
                    <h3 className="font-black text-lg uppercase">AI 智能评估报告 (本地模式)</h3>
                </div>
                <div className="prose prose-sm max-w-none font-mono text-sm leading-relaxed whitespace-pre-line">
                    {aiAnalysis || "正在生成分析..."}
                </div>
            </div>

            {/* Main Visuals Tab */}
            <div className="border-2 border-black bg-white">
                <div className="flex border-b-2 border-black">
                    <button 
                        onClick={() => setActiveVizTab('fit')}
                        className={`flex-1 py-3 text-sm font-bold uppercase flex items-center justify-center gap-2 ${activeVizTab === 'fit' ? 'bg-black text-white' : 'hover:bg-gray-100'}`}
                    >
                        <Activity className="w-4 h-4" /> 预测拟合
                    </button>
                    <button 
                        onClick={() => setActiveVizTab('feature')}
                        className={`flex-1 py-3 text-sm font-bold uppercase flex items-center justify-center gap-2 ${activeVizTab === 'feature' ? 'bg-black text-white' : 'hover:bg-gray-100'}`}
                    >
                        <BarChart3 className="w-4 h-4" /> 特征重要性
                    </button>
                    <button 
                        onClick={() => setActiveVizTab('radar')}
                        className={`flex-1 py-3 text-sm font-bold uppercase flex items-center justify-center gap-2 ${activeVizTab === 'radar' ? 'bg-black text-white' : 'hover:bg-gray-100'}`}
                    >
                        <PieChart className="w-4 h-4" /> 模型对比
                    </button>
                </div>

                <div className="p-6 h-[400px]">
                    {activeVizTab === 'fit' && (
                        <ResponsiveContainer width="100%" height="100%">
                            <ComposedChart data={PREDICTION_DATA}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                                <XAxis dataKey="month" tick={{fontSize: 12}} />
                                <YAxis />
                                <Tooltip contentStyle={{ border: '2px solid black', borderRadius: '0px' }} />
                                <Legend />
                                <Bar dataKey="actual" fill="#e5e7eb" stroke="#000" strokeWidth={1} name="实际销售额" barSize={40} />
                                <Line type="monotone" dataKey="predicted" stroke="#000" strokeWidth={3} dot={{r: 4, fill: '#000'}} name="预测销售额" />
                            </ComposedChart>
                        </ResponsiveContainer>
                    )}
                    
                    {activeVizTab === 'feature' && (
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={FEATURE_IMPORTANCE_DATA} layout="vertical" margin={{left: 40}}>
                                <CartesianGrid strokeDasharray="3 3" horizontal={false} />
                                <XAxis type="number" />
                                <YAxis dataKey="name" type="category" width={100} tick={{fontSize: 11}} />
                                <Tooltip contentStyle={{ border: '2px solid black' }} cursor={{fill: '#f3f4f6'}} />
                                <Bar dataKey="importance" fill="#000" name="重要性得分" barSize={20} />
                            </BarChart>
                        </ResponsiveContainer>
                    )}

                    {activeVizTab === 'radar' && (
                        <ResponsiveContainer width="100%" height="100%">
                            <RadarChart outerRadius={120} data={RADAR_DATA}>
                                <PolarGrid />
                                <PolarAngleAxis dataKey="subject" tick={{ fontSize: 12, fontWeight: 'bold' }} />
                                <PolarRadiusAxis angle={30} domain={[0, 100]} />
                                <Radar name="当前模型" dataKey="A" stroke="#000" strokeWidth={3} fill="#000" fillOpacity={0.2} />
                                <Radar name="基准模型 (Baseline)" dataKey="B" stroke="#9ca3af" strokeWidth={2} fill="#9ca3af" fillOpacity={0.1} />
                                <Legend />
                            </RadarChart>
                        </ResponsiveContainer>
                    )}
                </div>
            </div>
         </div>

         {/* Right: Leaderboard & Actions */}
         <div className="lg:col-span-1 space-y-6">
            <div className="bg-white border-2 border-black p-0 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
                <div className="p-4 border-b-2 border-black bg-gray-50">
                    <h3 className="font-bold flex items-center gap-2">
                         <Trophy className="w-5 h-5 text-yellow-600" /> 模型排行榜
                    </h3>
                </div>
                <div className="max-h-[300px] overflow-auto">
                    <table className="w-full text-left">
                        <thead className="bg-white border-b border-black text-xs uppercase sticky top-0">
                            <tr>
                                <th className="p-3">Model</th>
                                <th className="p-3 text-right">Acc</th>
                                <th className="p-3 text-right">R2</th>
                            </tr>
                        </thead>
                        <tbody>
                            {results.map((model) => (
                                <tr 
                                    key={model.id} 
                                    onClick={() => setSelectedResultModel(model.id)}
                                    className={`cursor-pointer hover:bg-gray-100 font-mono text-sm border-b border-gray-100 ${selectedResultModel === model.id ? 'bg-black text-white hover:bg-black' : ''}`}
                                >
                                    <td className="p-3 font-bold">{model.name}</td>
                                    <td className="p-3 text-right">{model.accuracy}%</td>
                                    <td className="p-3 text-right">{model.r2}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            <div className="bg-white border-2 border-black p-6">
                <h3 className="text-sm font-bold uppercase mb-4 text-gray-500">后续操作</h3>
                
                {!isPackaged ? (
                    <button 
                        onClick={handlePackage}
                        disabled={isUnfitProject}
                        className="w-full mb-3 bg-black text-white border-2 border-black py-3 font-bold flex items-center justify-center gap-2 hover:bg-white hover:text-black transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        <Package className="w-4 h-4" />
                        {isUnfitProject ? '精度不足无法打包' : '打包模型'}
                    </button>
                ) : (
                    <div className="bg-green-50 border-2 border-green-600 p-4 text-center mb-3">
                        <p className="font-bold text-green-800 flex items-center justify-center gap-2">
                            <CheckCircle2 className="w-5 h-5" /> 打包成功
                        </p>
                    </div>
                )}
                
                <button 
                    onClick={() => setReportOpen(true)}
                    className="w-full flex items-center justify-center gap-2 bg-white text-black border-2 border-black py-3 font-bold hover:bg-gray-50"
                >
                    <FileText className="w-4 h-4" />
                    查看详细评估报告
                </button>
            </div>
         </div>
      </div>
    </div>
  );
};
